spring:
  datasource:
    url: jdbc:${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration